export const promoDataSchema = [
  {
    key: 'card1_title',
    label: 'Заголовок первой карточки',
    type: 'text',
    default: 'Горячая пицца',
    editable: true,
  },
  {
    key: 'card1_desc',
    label: 'Описание первой карточки',
    type: 'text',
    default: 'Доставка за 30 минут',
    editable: true,
  },
  {
    key: 'card1_img',
    label: 'Изображение первой карточки',
    type: 'image',
    default: '/images/9.webp',
    editable: true,
  },
  {
    key: 'card2_title',
    label: 'Заголовок второй карточки',
    type: 'text',
    default: '2 по цене 1',
    editable: true,
  },
  {
    key: 'card2_desc',
    label: 'Описание второй карточки',
    type: 'text',
    default: 'Только сегодня',
    editable: true,
  },
  {
    key: 'card2_img',
    label: 'Изображение второй карточки',
    type: 'image',
    default: '/images/9.webp',
    editable: true,
  },
  {
    key: 'card3_title',
    label: 'Заголовок третьей карточки',
    type: 'text',
    default: 'Бесплатный напиток',
    editable: true,
  },
  {
    key: 'card3_desc',
    label: 'Описание третьей карточки',
    type: 'text',
    default: 'К каждому заказу',
    editable: true,
  },
  {
    key: 'card3_img',
    label: 'Изображение третьей карточки',
    type: 'image',
    default: '/images/9.webp',
    editable: true,
  },
  {
    key: 'card4_title',
    label: 'Заголовок четвертой карточки',
    type: 'text',
    default: 'Новинка',
    editable: true,
  },
  {
    key: 'card4_desc',
    label: 'Описание четвертой карточки',
    type: 'text',
    default: 'Пицца с трюфелем',
    editable: true,
  },
  {
    key: 'card4_img',
    label: 'Изображение четвертой карточки',
    type: 'image',
    default: '/images/9.webp',
    editable: true,
  },
  {
    key: 'card5_title',
    label: 'Заголовок пятой карточки',
    type: 'text',
    default: 'Скидка -15%',
    editable: true,
  },
  {
    key: 'card5_desc',
    label: 'Описание пятой карточки',
    type: 'text',
    default: 'На комбо-наборы',
    editable: true,
  },
  {
    key: 'card5_img',
    label: 'Изображение пятой карточки',
    type: 'image',
    default: '/images/9.webp',
    editable: true,
  },
  {
    key: 'card6_title',
    label: 'Заголовок шестой карточки',
    type: 'text',
    default: 'Супер сырная',
    editable: true,
  },
  {
    key: 'card6_desc',
    label: 'Описание шестой карточки',
    type: 'text',
    default: 'Премиум рецепт',
    editable: true,
  },
  {
    key: 'card6_img',
    label: 'Изображение шестой карточки',
    type: 'image',
    default: '/images/9.webp',
    editable: true,
  },
]
