export const promoStoriesDataSchema = [
  {
    key: 'item1_title',
    label: 'Название истории 1',
    type: 'text',
    default: 'Горячая пицца',
    editable: true,
  },
  {
    key: 'item1_image',
    label: 'Изображение истории 1',
    type: 'image',
    category: 'promo_stories',
    default: '/images/9.webp',
    editable: true,
  },
  {
    key: 'item1_link',
    label: 'Ссылка истории 1',
    type: 'text',
    default: '/?view=product&slug=pizza-5ccad6',
    editable: true,
  },
  {
    key: 'item2_title',
    label: 'Название истории 2',
    type: 'text',
    default: '2 по цене 1',
    editable: true,
  },
  {
    key: 'item2_image',
    label: 'Изображение истории 2',
    type: 'image',
    category: 'promo_stories',
    default: '/images/9.webp',
    editable: true,
  },
  {
    key: 'item2_link',
    label: 'Ссылка истории 2',
    type: 'text',
    default: '/?view=product&slug=pizza-fbede4',
    editable: true,
  },
  {
    key: 'item3_title',
    label: 'Название истории 3',
    type: 'text',
    default: 'Бесплатный напиток',
    editable: true,
  },
  {
    key: 'item3_image',
    label: 'Изображение истории 3',
    type: 'image',
    category: 'promo_stories',
    default: '/images/9.webp',
    editable: true,
  },
  {
    key: 'item3_link',
    label: 'Ссылка истории 3',
    type: 'text',
    default: '/?view=cart',
    editable: true,
  },
  {
    key: 'item4_title',
    label: 'Название истории 4',
    type: 'text',
    default: 'Новинка',
    editable: true,
  },
  {
    key: 'item4_image',
    label: 'Изображение истории 4',
    type: 'image',
    category: 'promo_stories',
    default: '/images/9.webp',
    editable: true,
  },
  {
    key: 'item4_link',
    label: 'Ссылка истории 4',
    type: 'text',
    default: '/?view=product&slug=pizza-5ccad6',
    editable: true,
  },
  {
    key: 'item5_title',
    label: 'Название истории 5',
    type: 'text',
    default: 'Скидка -15%',
    editable: true,
  },
  {
    key: 'item5_image',
    label: 'Изображение истории 5',
    type: 'image',
    category: 'promo_stories',
    default: '/images/9.webp',
    editable: true,
  },
  {
    key: 'item5_link',
    label: 'Ссылка истории 5',
    type: 'text',
    default: '/?view=product&slug=pizza-fbede4',
    editable: true,
  },
  {
    key: 'item6_title',
    label: 'Название истории 6',
    type: 'text',
    default: 'Супер сырная',
    editable: true,
  },
  {
    key: 'item6_image',
    label: 'Изображение истории 6',
    type: 'image',
    category: 'promo_stories',
    default: '/images/9.webp',
    editable: true,
  },
  {
    key: 'item6_link',
    label: 'Ссылка истории 6',
    type: 'text',
    default: '/?view=cart',
    editable: true,
  },
  {
    key: 'item7_title',
    label: 'Название истории 7',
    type: 'text',
    default: 'Премиум сет',
    editable: true,
  },
  {
    key: 'item7_image',
    label: 'Изображение истории 7',
    type: 'image',
    category: 'promo_stories',
    default: '/images/9.webp',
    editable: true,
  },
  {
    key: 'item7_link',
    label: 'Ссылка истории 7',
    type: 'text',
    default: '/?view=product',
    editable: true,
  },
  {
    key: 'item8_title',
    label: 'Название истории 8',
    type: 'text',
    default: 'Доставка бесплатно',
    editable: true,
  },
  {
    key: 'item8_image',
    label: 'Изображение истории 8',
    type: 'image',
    category: 'promo_stories',
    default: '/images/9.webp',
    editable: true,
  },
  {
    key: 'item8_link',
    label: 'Ссылка истории 8',
    type: 'text',
    default: '/?view=cart',
    editable: true,
  },
]

