export const deliveryDataSchema = [
  {
    key: 'section_title',
    label: 'Заголовок секции',
    type: 'text',
    default: 'Доставка и оплата в Анапе',
    editable: true,
  },
  {
    key: 'banner_title',
    label: 'Заголовок баннера',
    type: 'text',
    default: '60 МИНУТ ИЛИ ПИЦЦА БЕСПЛАТНО',
    editable: true,
  },
  {
    key: 'banner_line1',
    label: 'Описание 1',
    type: 'text',
    default: 'Если не успеем доставить за 60 минут, вы получите извинительную пиццу. Её можно будет добавить в один из следующих заказов.',
    editable: true,
  },
  {
    key: 'banner_line2',
    label: 'Описание 2',
    type: 'text',
    default: 'Все цены в меню указаны без учета скидок.',
    editable: true,
  },
  {
    key: 'min_order_value',
    label: 'Минимальная сумма',
    type: 'text',
    default: 'От 699₽',
    editable: true,
  },
  {
    key: 'min_order_desc',
    label: 'Подпись минимальной суммы',
    type: 'text',
    default: 'Минимальная сумма доставки',
    editable: true,
  },
  {
    key: 'max_cash_value',
    label: 'Максимальная сумма',
    type: 'text',
    default: '5 000₽',
    editable: true,
  },
  {
    key: 'max_cash_desc',
    label: 'Подпись максимальной суммы',
    type: 'text',
    default: 'Максимальная сумма при оплате наличными',
    editable: true,
  },
  {
    key: 'info_footer',
    label: 'Нижняя подпись',
    type: 'text',
    default: 'Изображения продуктов могут отличаться от продуктов в заказе.',
    editable: true,
  },
  {
    key: 'map_title',
    label: 'Заголовок карты',
    type: 'text',
    default: 'ЗОНА ДОСТАВКИ ОГРАНИЧЕНА',
    editable: true,
  },
  {
    key: 'map_image',
    label: 'Изображение карты',
    type: 'image',
    default: '/images/7.webp',
    editable: true,
  },
]
